remote_theme: Iseratho/panthera-jekyll
title: Markus Reiter-Haas
subtitle: "University Assistant <br />@Graz University of Technology"
description: Personal Github Page of Markus Reiter-Haas
plugins:
  - jekyll-seo-tag

menu:
  - text: About
    link: /
    icon: fas fa-user-circle

  - text: CV
    link: /cv
    icon: fas fa-id-card

  - text: Research
    link: /research
    icon: fas fa-vial

  - text: PhD Project
    link: /phd
    icon: fas fa-project-diagram

  - text: PhD Thesis
    link: /thesis
    icon: fas fa-book

  - text: Teaching
    link: /teaching
    icon: fas fa-chalkboard-teacher

  - text: Blog Posts
    link: /posts
    icon: fas fa-pen

# - text: Education
#   link: "#education"
#   icon: fas fa-graduation-cap

# - text: Experience
#   link: "#experience"
#   icon: fas fa-briefcase
    
#   - text: Publications
#     link: "#publications"
#     icon: fas fa-file-alt

social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/markus-reiter-haas/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/Iseratho
    icon: fab fa-github-square

  - name: twitter
    link: https://www.twitter.com/Iseratho
    icon: fab fa-twitter-square
    
  - name: mastodon
    link: https://mastodon.online/@iseratho
    icon: fab fa-mastodon

  - name: scholar
    link: https://scholar.google.at/citations?user=IN-hA_gAAAAJ
    icon: fas fa-graduation-cap

  - name: orcid
    link: https://orcid.org/my-orcid?orcid=0000-0001-9852-8206
    icon: fab fa-orcid

  - name: scholar
    link: https://www.researchgate.net/profile/Markus-Reiter-Haas
    icon: fab fa-researchgate
