remote_theme: christianezeani/panthera-jekyll
title: Markus Reiter-Haas
subtitle: "University Assistant\n@Graz University of Technology"
description: Personal Github Page of Markus Reiter-Haas

menu:
  - text: Profile
    link: "#profile"
    icon: fas fa-user-circle
    
  - text: Publications
    link: "#publications"
    icon: fas fa-file-alt

social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/markus-reiter-haas/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/Iseratho
    icon: fab fa-github-square

  - name: twitter
    link: https://www.twitter.com/Iseratho
    icon: fab fa-twitter
