remote_theme: christianezeani/panthera-jekyll
title: Markus Reiter-Haas
subtitle: "University Assistant <br />@Graz University of Technology"
description: Personal Github Page of Markus Reiter-Haas
plugins:
  - jekyll-seo-tag

menu:
#   - text: Profile
#     link: "#profile"
#     icon: fas fa-user-circle

  - text: Teaching
    link: "#teaching"
    icon: ""
    
  - text: Education
    link: "#education"
    icon: fas fa-graduation-cap

  - text: Experience
    link: "#experience"
    icon: fas fa-briefcase

  - text: Blog Posts
    link: /posts
    icon: ""
    
#   - text: Publications
#     link: "#publications"
#     icon: fas fa-file-alt
    
  - text: CV
    link: /markdown-cv
    icon: ""

social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/markus-reiter-haas/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/Iseratho
    icon: fab fa-github-square

  - name: twitter
    link: https://www.twitter.com/Iseratho
    icon: fab fa-twitter-square
    
  - name: mastodon
    link: https://mastodon.online/@iseratho
    icon: fab fa-mastodon

  - name: scholar
    link: https://scholar.google.at/citations?user=IN-hA_gAAAAJ
    icon: fab fa-google
